name: sql-bak

services:
  sqlcmd:
    extends:
      service: sqlcmd
      file: "./sqlcmd/compose.yaml"
  mc:
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

volumes:
  mssql:
    name: mssql
    external: true
  sepidardb:
    name: sepidardb
    external: true

networks:
  mssql:
    name: mssql
    external: true
