services:
  sqlcmd:
    env_file:
      - .env
    extends:
      service: sqlcmd
      file: "./sqlcmd/compose.yaml"
  mc:
    env_file:
      - .env
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    env_file:
      - .env
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

volumes:
  mssql:
    name: mssql
    external: true

networks:
  mssql:
    name: mssql
    driver: overlay
    attachable: true
    external: true

configs:
  mc:
    name: mc
    file: "./mc/config.json"
  ofelia:
    name: ofelia
    file: "./ofelia/config.ini"
  db-bak-full:
    name: db-bak-full
    file: "./sqlcmd/db-bak-full.sh"
  db-bak-diff:
    name: db-bak-diff
    file: "./sqlcmd/db-bak-diff.sh"
