name: ${NAME}

services:
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools
    restart: unless-stopped
    entrypoint: /usr/bin/tail
    command: -f /dev/null
    environment:
      - NAME=${NAME}
      - ADDRESS=${ADDRESS}
      - PASSWORD=${PASSWORD}
      - S3URL=${S3URL}
      - S3BUCKET=${S3BUCKET}
      - DB1=${DB1}
      - DB2=${DB2}
    network_mode: host
    volumes:
      - "./dbbakscripts:/var/dbbakscripts"
      - "/etc/localtime:/etc/localtime:ro"

  ofelia:
    image: mcuadros/ofelia
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
    network_mode: host
    volumes:
      - "./config.ini:/etc/ofelia/config.ini"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
