services:
  mc:
    image: ${REGISTRY}/mc
    runtime: crun
    restart: always
    command: mirror --overwrite /var/mssql/ oncolog/sto-db/
    network_mode: host
    configs:
      - source: mc
        target: /root/.mc/config.json
    volumes:
      - type: volume
        read_only: true
        source: mssql
        target: /var/mssql/
