services:
  mc:
    image: reg.oncolog.ir/mc
    restart: always
    container_name: mc-mssql
    entrypoint: /usr/bin/tail
    command: -f /dev/null
    network_mode: host
    volumes:
      - "./config.json:/root/.mc/config.json"
      - "mssql:/var/mssql:ro"
      - "sepidardb:/var/sepidardb:ro"
