services:
  mc:
    image: ${REGISTRY}/mc
    runtime: runc
    restart: always
    container_name: mc-mssql
    entrypoint: tail
    command: -f /dev/null
    network_mode: host
    configs:
      - source: mc
        target: /root/.mc/config.json
    volumes:
      - type: volume
        read_only: true
        source: mssql
        target: /var/mssql/
