services:
  sqlcmd:
    image: reg.oncolog.ir/mssql-tools
    restart: always
    container_name: sqlcmd
    entrypoint: /usr/bin/tail
    command: -f /dev/null
    networks:
      - mssql
    volumes:
      - "./sqlcmd/db-bak-full.sh:/var/db-bak-full.sh"
      - "./sqlcmd/db-bak-diff.sh:/var/db-bak-diff.sh"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
