services:
  sqlcmd:
    image: ${REGISTRY}/mssql-tools
    runtime: runc
    restart: always
    entrypoint: tail
    container_name: sqlcmd
    command: -f /dev/null
    environment:
      SUB: ${SUB}
    networks:
      - mssql
    configs:
      - source: db-bak-full
        target: /var/db-bak-full.sh
      - source: db-bak-diff
        target: /var/db-bak-diff.sh
    volumes:
      - type: bind
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
      - type: bind
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
